fix(cli): prevent shadowed error function
Because the error function was shadowed by the caught error, you'd see an error like:

Error: error is not a function

This prevents the error function from being shadowed so that it is still callable.